<?php if ($_SESSION['usuario']['tipo'] == "administrador") {
    $producto = Obtener(T_PRODUCTO, $lfmc['link'][3]);
?>
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">
                Actualizar producto
            </h2>
        </div>
        <div class="card-body">
            <form id="actualizar" enctype="multipart/form-data">
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="fecha">Fecha de entrega</label>
                        <input type="date" name="fecha" class="form-control" value="<?php echo $producto['fecha'] ?>" placeholder="Fecha" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="marca_id">Marca</label>
                        <select class="custom-select form-control-border border-width-2" name="marca_id">
                            <option value="" selected>- Seleccione -</option>
                            <?php $marcas = ObtenerTodos(T_marca);
                            foreach ($marcas as $marca) { ?>
                                <option value="<?php echo $marca['id'] ?>"<?php echo ($marca['id'] == $producto['marca_id']) ? 'selected' : '' ?>>
                                    <?php echo $marca['nombre'] ?>
                                </option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="nombre">Nombre</label>
                        <input type="text" name="nombre" value="<?php echo $producto['nombre'] ?>" class="form-control" placeholder="Nombre" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="modelo">Modelo de Equipo</label>
                        <input type="text" name="modelo" value="<?php echo $producto['modelo'] ?>" class="form-control" placeholder="modelo" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="serial">Serial</label>
                        <input type="text" name="serial" value="<?php echo $producto['serial'] ?>" class="form-control" placeholder="Serial" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="departamento">Departamento</label>
                        <input type="text" name="departamento" value="<?php echo $producto['departamento'] ?>" class="form-control" placeholder="Departamento" required>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="trabajador">Nombre del Trabajador</label>
                        <input type="text" name="trabajador" value="<?php echo $producto['trabajador'] ?>" class="form-control" placeholder="Nombre del Trabajador" required>
                    </div>
                </div>

                <div class="col-12 text-center">
                    <button class="btn btn-success" id="btn_add" type="submit">Actualizar</button>
                </div>
            </form>
        </div>
    </div>
    <script>
        $(function() {
            var actualizar = $("#actualizar");
            actualizar.on("submit", function(e) {
                e.preventDefault();
                var formData = new FormData(document.getElementById("actualizar"));
                $.ajax({
                    url: "<?php echo CargarEnlace('nucleo/ajax/catalogos/producto-actualizar.php') ?>",
                    type: "POST",
                    dataType: "json",
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    beforeSend: function(dato) {
                        $("#btn_edit").html('Actualizando...');
                        actualizar.find('button[type="submit"]').attr('disabled', 'true');
                    }
                }).done(function(dato) {
                    if (dato.estado == 200) {
                        toastr.success(dato.mensaje);
                        setTimeout(function() {
                            window.location.href = '<?php echo CargarEnlace('catalogos/productos'); ?>';
                        }, 1000);
                    } else {
                        toastr.error(dato.mensaje);
                    }
                }).fail(function(dato) {
                    toastr.error('😅 Algo salio mal');
                });
                $("#btn_edit").html('Actualizar');
                actualizar.find('button[type="submit"]').removeAttr('disabled');
            });
        });
    </script>
<?php } else {
    echo CargarPagina('403/contenido');
} ?>