<?php if ($_SESSION['usuario']['tipo'] == "administrador") {
    $usuarios = ObtenerTodos(T_USUARIO); ?>
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">
                Usuarios
            </h2>
            <div class="card-tools">
                <ul class="nav nav-pills ml-auto">
                    <li class="nav-item">
                        <a class="btn btn-success" href="<?php echo CargarEnlace('configuracion/usuarios/nuevo') ?>">
                            <i class="fas fa-user-plus"></i> Agregar
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="card-body">
            <?php if ($usuarios) { ?>
                <div class="msg" style="margin:-10px 15px;"></div>
                <table class="table table-bordered table-hover dataTable dtr-inline" id="tablaUsuarios">
                    <thead>
                        <tr>
                            <th>Usuario</th>
                            <th>Nombre</th>
                            <th>Tipo</th>
                            <th class="text-center"><i class="fas fa-bars"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($usuarios as $usuario) { ?>
                            <tr id="<?php echo $usuario['id'] ?>">
                                <td>
                                    <?php echo $usuario['usuario'] ?>
                                </td>
                                <td>
                                    <?php echo TextoCorto($usuario['nombre'], 70) ?>
                                </td>
                                <td>
                                    <?php echo ucfirst($usuario['tipo']) ?>
                                </td>
                                <td class="text-center">
                                    <?php if ($_SESSION['usuario']['id'] != $usuario['id']) { ?>
                                        <button id="btn<?php echo $usuario['id'] ?>" class="btn btn-danger" onclick="eliminar('<?php echo $usuario['id'] ?>','<?php echo $usuario['nombre'] ?>')" title="Anular"><i class="fas fa-trash-alt"></i></button>
                                    <?php } ?>
                                    <a class="btn btn-warning" href="<?php echo CargarEnlace('configuracion/usuarios/editar/' . $usuario['id']) ?>" title="Editar"><i class="fas fa-edit"></i></a>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            <?php } else { ?>
                <div>Sin datos</div>
            <?php } ?>
        </div>
    </div>
    <script>
        $('#tablaUsuarios').DataTable({
            language: TablaIdioma
        });

        function eliminar(id, nombre) {
            Swal.fire({
                title: '¿Estas seguro?',
                text: "Seguro desea anular el usuario: " + nombre,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'SI'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: "<?php echo CargarEnlace('nucleo/ajax/usuario/eliminar.php') ?>?id=" + id,
                        type: "GET",
                        dataType: "json",
                        cache: false,
                        contentType: false,
                        processData: false,
                        beforeSend: function(dato) {
                            $("#btn" + id).html('Eliminando');
                        }
                    }).done(function(dato) {
                        if (dato.estado == 200) {
                            $("#" + id).remove();
                            Swal.fire(
                                'Eliminado!',
                                'Se ha eliminado con éxito.',
                                'success'
                            )
                        } else {
                            Swal.fire(
                                'Error',
                                dato.mensaje,
                                'error'
                            )
                        }
                    }).fail(function(dato) {
                        $(".msg").html('');
                        Swal.fire(
                            'Error',
                            '😅 Algo salio mal',
                            'error'
                        )
                    });
                }
            })
        }
    </script>
<?php } else {
    echo CargarPagina('403/contenido');
} ?>