<div class="error-page">
    <h2 class="headline text-warning"> 404</h2>

    <div class="error-content">
        <h3><i class="fas fa-exclamation-triangle text-warning"></i> ¡Vaya! Página no encontrada.</h3>

        <p>
        No hemos podido encontrar la página que buscabas.
        Mientras tanto, puede <a href="<?php echo CargarEnlace();?>">volver al inicio</a>
        </p>
    </div>
</div>